name = "Penny"
license = "MIT"
licenselink = "https://github.com/davidwinter/penny/blob/main/LICENSE"
description = "a minimalist hugo theme"
homepage = "https://github.com/davidwinter/penny"
tags = []
features = []
min_version = "0.54.0"

[author]
  name = "David Winter"
  homepage = "https://davidwinter.dev"
